### ISSUE TITLE
valohai-utils input .path() and .paths() should support wildcards.

### ISSUE THREAD

**Issue by JuhaKiili** [valohai/valohai-utils#54]
It is quite annoying to find a single file from an input with potentially many files.

Today you are forced to write things like:
```
import fnmatch
for path in fnmatch.filter(valohai.inputs("myinput").paths(), "weights*.pb"):
  print(path)
```

It should be:
```
my_file = valohai.inputs("myinput").path("weights*.pb")
```

**Comment by orasimus** [comment]
I think the `.path(name)` usage should have a different API.

I've yet to clarify my complete thoughts on a separate ticket, but basically I think the functionality should be:
- inputs('dataset').path(process_archives=False) -> archive.zip or file.data or dataset/ (if multiple files)
- inputs('dataset').path(process_archives=True) -> file.data or archive/ (if multiple files)
- inputs('dataset').paths(process_archives=False) -> [file1.data, archive.zip, archive2.zip]
- inputs('dataset').paths(process_archives=True) -> [file1.data, archive/file2.data, archive/file3.data, archive2/file4.data]

This is already complex, so adding the option to give a string that filters the paths down would make it even more complex.

If we want to provide the filtering mechanism built-in, how about a different method, like `vh.inputs('dataset').filter('weights*.pb')`

**Comment by akx** [comment]
I think all of the `paths`/`streams`/... methods should just support a filter argument; if a string, an `fnmatch` expression, and if a function, a predicate:

```
valohai.inputs("myinput").paths(filter="*.pb")
valohai.inputs("myinput").paths(filter=lambda vfs_file: vfs_file.name[3].isupper())
```
